"""
Django settings for plaintes project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/

"""

import os
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9zf=gd@@1p%t9@pl61pmkt%+(+=@76g%t8vt7vgeb65a6q1=lo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.8.124','ec2-3-13-36-233.us-east-2.compute.amazonaws.com','3.13.36.233', 'finexsapp.com','127.0.0.1','finexs.app.ngrok.io','radd.serveo.net' ]


# Application definition

INSTALLED_APPS = [
    #'django_select2',
    #'dal',
    #'dal_select2',
    #'suit',
    'account',
    'grappelli',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    'bootstrap_datepicker',
    'tempus_dominus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',
    'plaintes_app',
    'chauffeur_app',
    'mtickets_apps',
    'pneus_app',
    'django_filters',
    'cars_app',
    'colis_apps',
    'archivages_app',
    'import_export',
    'crispy_forms',
    'storages',
    'gunicorn',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'plaintes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plaintes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'suite',
        'USER': 'finexs',
        'PASSWORD': '14septembre',
        'HOST':'localhost',
        'PORT':'5432'
    },
    'old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Cache
CACHE_TTL = 60 * 15

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# envoie emails console
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# envoie emails 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'send.one.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'finexs-informatique@finexsvoyages.net'
EMAIL_HOST_PASSWORD = '(Qw3rty.)'
EMAIL_USE_TLS = True
#Cette ligne de code est essentielle pour reset le password
DEFAULT_FROM_EMAIL = 'finexs-informatique@finexsvoyages.net'



AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = 'scanfinexs'
#AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/statics/'
#The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.
#La ligne ci dessus me pousse a commenter la ligne ci dessous (pris dans l'appli streaming)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'statics'), ]
# J'ai eu un soucis , j'ai commente la ligne en dessous mais c'est elle qui est ok .
#STATIC_ROOT = os.path.join(BASE_DIR, 'statics/') 

# Dossier des medias (images , videos )

#Decommmente pour stockage local ? Je ne crois pas .
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

#stockage aws s3
DEFAULT_FILE_STORAGE = 'plaintes.storage_backends.MediaStorage'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

BOOTSTRAP4 = {
    'include_jquery': True,
}

# Accounts
LOGIN_REDIRECT_URL = 'colis_apps:homeredirect'

#if True :
LOGIN_URL = 'account:login'

LOGOUT_URL = 'account:logout'

# Celery
CELERY_BROKER_URL = 'amqp://localhost'

# Other Celery settings
CELERY_BEAT_SCHEDULE = {
    'task-number-one': {
        'task': 'archivages_app.tasks.alert',
        #'schedule': crontab(minute=0, hour='6'),
        'schedule': 30.0
    }
}

# Affaire de Sessions 

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 900 # set just 10 seconds to test
SESSION_SAVE_EVERY_REQUEST = True